import time

def slowprint(text, delay=0.03):
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()

day = 4
gift = "none"
name = "Sqiggles is awesome"

if day == 4:
    slowprint("You wake up, looking at your calendar.")
    time.sleep(0.3)
    slowprint("It's the 7th. Today is finally the day.")
    time.sleep(0.3)
    slowprint("You grab your bag as you make your way to the front door.")
    time.sleep(0.3)
    slowprint("You can barely step outside before you hear your name being called.")
    time.sleep(0.3)
    slowprint(f"'{name}! I haven't seen you in forever!'")
    time.sleep(0.3)
    slowprint("You look up at Scarlet, a smile slowly showing on your face.")
    time.sleep(0.3)
    slowprint("Scarlet makes her way up to you, standing face to face in the matter of seconds.")
    time.sleep(0.3)

    if gift == "none":
        slowprint("'Do you know what day it is?' She beamed, looking at you with hope.")
        time.sleep(0.3)
        slowprint("Your smile quickly turns to a frown before you can stop yourself.")
        time.sleep(0.3)
        slowprint("'Oh, yah.'")
        time.sleep(0.3)
        slowprint("You notice Scarlets shoulders slump, despite how upbeat she trys to stay.")
        time.sleep(0.3)
        slowprint("She opens her mouth to say something, but she changes her mind before she can.")
        time.sleep(0.3)
        slowprint("There's an uncomfortable pause between you two, before she lets out a sigh.")
        time.sleep(0.3)
        slowprint("'Well, atleast I got to finally see you.'")
        time.sleep(0.3)
        slowprint("Before you gain the courage to say anything she turns and leaves.")
        time.sleep(0.3)
        slowprint("You watch helplessly as she walks to her car, looking glum as she drives away.")
        time.sleep(0.3)
        slowprint("You make your way back inside, the sound of rain starts up as you make your way back into the house.")
        time.sleep(0.3)
        slowprint("You to your bedroom, tossing your bag to the floor as you slump onto your bed.")
        time.sleep(1)
        slowprint("You lay there for a while, at least it feels that way.")
        time.sleep(0.3)
        slowprint("You hear your computer beep, but you don't bother to look at it.")
        time.sleep(0.3)
        slowprint("Theres always next year.")
        time.sleep(0.3)
        slowprint("Ending 1")
        slowprint("Giftless and lonely")

    if gift == "Necklace" or gift == "Silver earrings":
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        time.sleep(0.3)
        slowprint("")
        
    if gift == "book":
        slowprint("hi")